apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb
spec:
  replicas: 1
  selector:
    matchLabels:
      myApp: postgres #this label is going to select the label of the pods, so must have the same label as 'myApp' and 'postgres'
  template:
    metadata:
      labels:
        myApp: postgres #this label should match with the deployment selector above
    spec:
      containers: #we can have more than 1 container in the pod
        - name: postgresdb
          image: postgres:14-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: '12345'
            - name: POSTGRES_DB
              value: msvc_courses
          volumeMounts:
            - name: data-postgres
              mountPath: /var/lib/mysql
      volumes:
        - name: data-postgres
          persistentVolumeClaim:
            claimName: postgres-pvc

