apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  storageClassName: ""
  #storageClassName: ""
  accessModes:
    - ReadWriteMany
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-08c276dddd1a96b43
    #- ReadWriteOnce
 # hostPath:
 #   path: /var/lib/mysql
 #   type: DirectoryOrCreate